#  
# 
#  https://alacritty.org/config-alacritty.html
#


# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/hardhacker.toml"]

[font]
size = 12

[font.normal]
#family = "UbuntuMono Nerd Font"
family = "Source Code Pro"

[window]
decorations = "none"

[window.padding]
x = 10
y = 10
