#  
# 
#  https://alacritty.org/config-alacritty.html
#


# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/hardhacker.toml"]

[font]
size = 12

[font.normal]
#family = "UbuntuMono Nerd Font"
family = "SauceCodePro Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
  { key = "C",  mods = "Alt",           chars = "\u001bc"                       },
  { key = "H",  mods = "Alt",           chars = "\u001bh"                       },
  { key = "J",  mods = "Alt",           chars = "\u001bj"                       },
  { key = "K",  mods = "Alt",           chars = "\u001bk"                       },
  { key = "L",  mods = "Alt",           chars = "\u001bl"                       },
]


