#  
# 
#  https://alacritty.org/config-alacritty.html
#


# themes from https://github.com/alacritty/alacritty-theme
#import = ["~/.config/alacritty/themes/themes/hardhacker.toml"]
#import = ["~/.config/alacritty/themes/themes/falcon.toml"]
#import = ["~/.config/alacritty/themes/themes/google.toml"]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
#import = ["~/.config/alacritty/themes/themes/iterm.toml"]
#import = ["~/.config/alacritty/themes/themes/monokai_charcoal.toml"]
#import = ["~/.config/alacritty/themes/themes/seashells.toml"]

#[env]
#term = "xterm-256color"

[font]
size = 12.4

[font.normal]
#family = "UbuntuMono Nerd Font"
family = "SauceCodePro Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 2
y = 2

[keyboard]
bindings = [
  { key = "C", mods = "Alt", chars = "\u001bc" },
  { key = "H", mods = "Alt", chars = "\u001bh" },
  { key = "J", mods = "Alt", chars = "\u001bj" },
  { key = "K", mods = "Alt", chars = "\u001bk" },
  { key = "L", mods = "Alt", chars = "\u001bl" },
]
