return {

  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "bash-debug-adapter",
        "shellcheck",
        "shellharden",
        "beautysh",
        "clang-format",
        "clangd",
        "codelldb",
        "cpplint",
        "cpptools",
        "neocmakelsp",
        "cmakelang",
        "cmakelint",
        "checkmake",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "hadolint",
        "json-lsp",
        "fixjson",
        "jsonlint",
        "texlab",
        "latexindent",
        "bibtex-tidy",
        "markdownlint",
        "marksman",
        "pyright",
        "pyment",
        "pylint",
        "debugpy",
        "yaml-language-server",
        "yamlfix",
        "yamlfmt",
        "yamllint",
      },
    },
  },
}
